### ISSUE TITLE
Find or create a way to scrape RateMyProfessor

### ISSUE THREAD

**Issue by bnielsen1** [ufosc/Schedule_Helper#2]
Either create a way to scrape RateMyProfessor or see if this open-source API still works https://github.com/tisuela/ratemyprof-api

**Comment by ThundR67** [comment]
RateMyProfessor does have a graphql api. https://github.com/Michigan-Tech-Courses/rate-my-professors. This repo has implemented it in javascript, I believe. So, we will need to convert it into python.

**Comment by ThundR67** [comment]
I am on it on this repo:
https://github.com/ThundR67/RateMyProfessor.py

**Comment by ThundR67** [comment]
Can you tell me exactly what info we need to scap out?
